[Emulator]

# CacheEnabled set to true to enable loading apps from GCF. 
# If it is true, and a clientregistry.blob file is not supplied, 
# then you must supply revApps.ini file with the correct cache requirements. 
# See the example revApps.ini, however it is highly recommended that you use
# a clientregistry.blob file for maximum compatibility
#
# Default = False
#
CacheEnabled = false

# CachePath - set to the folder where your GCF files are located
CachePath = E:\Steam\SteamApps

# Language - rev emu will automagically load the correct language files. 
# This can be English, French, Italian, German, Spanish, sChinese, 
# Korean, Koreana, tChinese, Japanese, Russian, Thai, or Portugeuse
Language = Russian

# Change Logging to True to enable/disable log file output for steam.dll
Logging=True

# Change SteamDll to point to your official Steam client DLL.
# This setting is required for Steam UserID Validation functions
# to support legit Steam IDs.
#SteamDll=.\bin\Steam\Steam.dll

# Change SteamClient to True if you want to use the steamclient emulator.
SteamClient = True

# Change SteamUser to the steam username that you wish to use with revEmu
# Defaults to revCrew if not specified
#
SteamUser = SteamPlayer

[Log]

# If Logging is set to True, choose which functions would you like to log.
FileSystem=False
Account=False
UserID=False

[steamclient]

################################### NOTE ####################################
# These settings may apply even if you don't choose to use steamclient.dll! #
#############################################################################
#
# Change the setting below to set your PlayerName (used in src2007 engine)
# not use ""
#
# Default = REVOLUTiON
#
PlayerName=REVOLUTiON


# Change the setting below to enable/disable log file output for steamclient.dll
#
# Default = False
#
Logging=True

# Change ClientDLL to point to the original steamclient.dll
# This setting will enable VAC for your server and your server will be listed
# on Valve master server! Also, Steam clients will have their regular Steam IDs
# Please use the steamclient.dll from Steam folder!
#
# Default = (n/a)
#
#ClientDLL=.\bin\Steam\steamclient.dll

#SteamExe=E:\Steam\Steam.exe
#DisableUnlockedItems = True
#EnableSDK = True

#HL2 servers
#
MasterServer = 80.78.244.170:27011
#MasterServer = 63.234.149.83:27011
#MasterServer = 63.234.149.90:27011
#GameVersion = 1.0.0.40

ClanTag=[revcrew]

[GameServer]
AllowOldRev74=False
AllowOldRev=False
AllowUnknown=False
AllowCracked=False
#AllowLegit=False
AllowedAnyCountConnectUnknownClientWithOneIP = false

[GameServerNSNet]
#EnableNSNetSvc = [False/UDP/TCP/BOTH]
#NSNetDedicatedPort = Порт(Только для Slave серевров)
#AdditionalSlaveServer = IP:PORT
#AdditionalSlaveServer = IP:PORT
#AdditionalSlaveServer = IP:PORT
#AdditionalSlaveServer = IP:PORT
